In [1]:
#Loading required libraries
from bs4 import BeautifulSoup
import requests
import pandas as pd 
import numpy as np

from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

In [31]:
#set the time frame for data extraction.
from datetime import datetime, timedelta

start_date = datetime(2022, 1, 1)
end_date = datetime(2023, 6, 23)

date_format = "%d-%b-%Y"

date_list = []
current_date = start_date

while current_date <= end_date:
    if current_date.weekday() not in [5, 6]:  # Exclude Saturday (5) and Sunday (6)
        formatted_date = current_date.strftime(date_format)
        date_list.append(formatted_date)
    current_date += timedelta(days=1)

In [ ]:
date_list

In [3]:
url = "https://www.fpi.nsdl.co.in/web/Reports/traderepositoryreport.aspx"

In [38]:
#setting up selenium chrome driver
from selenium.webdriver.chrome.service import Service
s = Service("C:\\chromedriver.exe")
driver = webdriver.Chrome(service = s)
driver.get(url)

In [11]:
first_table = table[0].droplevel(0,axis = 1)
second_table = table[1].droplevel(0,axis = 1)

In [12]:
first_table.drop(index=first_table.index, inplace = True)
second_table.drop(index=second_table.index, inplace = True)

In [17]:
second_table

Empty DataFrame
Columns: [Exchange, Trade Date, ISIN, Listed/Unlisted Security, Issuer Name, Issue Description, Coupon (%), Maturity Date, Credit Rating, No. of Trades, Total Trade Value* in Rs. Lacs, Last Traded Price (in Rs.), Weighted Average Price, Weighted Average Yield, Remarks]
Index: []

In [32]:

#for i in date_list:
for i in date_list:
    e = driver.find_element(By.ID, "hdndrpview")
    driver.execute_script("arguments[0].setAttribute('value','1')", e)
    e = driver.find_element(By.ID, "hdnFromDate")
    driver.execute_script(f"arguments[0].setAttribute('value', '{i}')", e)
    driver.find_element(By.ID, "btnSubmit").click()
    
    time.sleep(3)
    
    html=driver.page_source
    soup=BeautifulSoup(html,'html.parser')
    div=soup.select_one("div#dvTradeData")
    table=pd.read_html(str(div))
    
    if table[0].empty == False:
        table1, table2 = table[0], table[1]
        first_table = first_table.append(table1.droplevel(0,axis = 1))
        if table[1].empty == False:
            second_table = second_table.append(table2.droplevel(0,axis = 1))
    else:
        continue

In [34]:
first_table

,Exchange,Trade Date,ISIN,Listed/Unlisted Security,Issuer Name,Issue Description,Coupon (%),Maturity Date,Credit Rating,No. of Trades,Total Trade Value* in Rs. Lacs,Last Traded Price (in Rs.),Weighted Average Price,Weighted Average Yield,Remarks
0,NSE,17-Nov-2020,INE774D08LU6,-,Mahindra & Mahindra Financial Services Limited,-,8.72,06-Jun-2026,-,1,0.02,1100.00,1.100000e+03,0.0,-
1,NSE,17-Nov-2020,INE774D08MA6,-,Mahindra & Mahindra Financial Services Limited,-,9.00,06-Jan-2026,-,6,0.41,1111.00,1.165714e+03,0.0,-
2,NSE,17-Nov-2020,INE261F07032,-,National Bank of Agriculture & Rural Development,-,7.64,23-Mar-2031,-,5,2.88,1280.00,1.281533e+03,0.0,-
3,NSE,17-Nov-2020,INE134E07588,-,Power Finance Corporation Limited,-,7.60,17-Oct-2035,-,7,7.46,1310.00,1.305622e+03,0.0,-
4,NSE,17-Nov-2020,INE787H07370,-,India Infrastructure Finance Company Limited,-,8.91,22-Jan-2034,-,34,20.40,1477.99,1.475102e+03,0.0,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,BSE,23-Jun-2023,INE540P07350,L,U.P.POWER CORPORATION LIMITED,UPPCL-10.15-20-1-28-PVT,10.15,20-Jan-2028,NaN,1,10.68,1067500.00,1.067500e+06,0.0,NaN
280,BSE,23-Jun-2023,INE540P07384,L,U.P.POWER CORPORATION LIMITED,UPPCL-9.7-31-03-27-PVT,9.70,31-Mar-2027,NaN,4,40.60,1015000.06,1.014900e+06,0.0,NaN
281,BSE,23-Jun-2023,INE540P07392,L,U.P.POWER CORPORATION LIMITED,UPPCL-9.70-31-3-28-PVT,9.70,31-Mar-2028,NaN,1,10.15,1014999.99,1.014999e+06,0.0,NaN
282,BSE,23-Jun-2023,INE540P07491,L,U.P.POWER CORPORATION LIMITED,UPPCL-9.95-29-3-30-PVT,9.95,29-Mar-2030,NaN,1,10.40,1040000.00,1.040000e+06,0.0,NaN
283,BSE,23-Jun-2023,INE540P07509,L,U.P.POWER CORPORATION LIMITED,UPPCL-9.95-31-3-31-PVT,9.95,31-Mar-2031,NaN,1,10.35,1035000.00,1.035000e+06,0.0,NaN

In [35]:
first_table.to_csv("first.csv")

In [36]:
second_table.to_csv("second.csv")

In [10]:
e = driver.find_element(By.ID, "hdndrpview")
driver.execute_script("arguments[0].setAttribute('value','1')", e)
e = driver.find_element(By.ID, "hdnFromDate")
driver.execute_script(f"arguments[0].setAttribute('value','09-May-2022')", e)
driver.find_element(By.ID, "btnSubmit").click()
html=driver.page_source
soup=BeautifulSoup(html,'html.parser')
div=soup.select_one("div#dvTradeData")
table=pd.read_html(str(div))

In [ ]:
#Data Cleaning
df = pd.read_csv(r"C:\Users\pk\Downloads\merged.csv")
#agency
def extract_credit_agency(row):
    row = str(row)
    agency = ''
    if 'CRISIL' in row:
        agency = 'CRISIL'
    elif 'ICRA' in row:
        agency = 'ICRA'
    elif 'CARE' in row:
        agency = 'CARE'
    elif 'ACUITE' in row:
        agency = 'ACUITE'
    elif 'IND' in row:
        agency = 'IND'
    elif 'BWR' in row:
        agency = 'BWR'
    elif 'Infomerics Valuation and Rating Pvt. Ltd' in row:
        agency = 'Infomerics Valuation and Rating Pvt. Ltd'
    if agency == '':
        agency = 'other'
    
    return agency

In [ ]:
# Define a function to extract the desired credit rating
def extract_credit_rating(row):
    row = str(row)
    rating = ''
    if 'CRISIL' in row:
        rating = row.split('CRISIL')[-1].split('/')[0].split(';')[0].strip()
    elif 'ICRA' in row:
        rating = row.split('ICRA')[-1].split('/')[0].split(';')[0].strip()
    elif 'CARE' in row:
        rating = row.split('CARE')[-1].split('/')[0].split(';')[0].strip()
    elif 'ACUITE' in row:
        rating = row.split('ACUITE')[-1].split('/')[0].split(';')[0].strip()
    elif 'IND' in row:
        rating = row.split('IND')[-1].split('/')[0].split(';')[0].strip()
    elif 'BWR' in row:
        rating = row.split('BWR')[-1].split('/')[0].split(';')[0].strip()
    elif 'Infomerics Valuation and Rating Pvt. Ltd' in row:
        rating = row.split('Infomerics Valuation and Rating Pvt. Ltd')[-1].split('/')[0].split(';')[0].strip()
    if rating == '':
        rating = row
        
    rating = re.sub(r'\(.*?\)|\[.*?\]', '', rating)
    rating = rating.replace('STABLE', '')
    rating = rating.replace(' Negative', '-')
    rating = rating.replace('Stable', '')
    rating = rating.replace(r'/Stable', '')
    rating = rating.replace(r'r', '')
    rating = rating.replace(r'/', '')
    rating = rating.replace('IRR', '')
    rating = rating.replace('IVR', '')
    rating = rating.replace('PP-MLD', '')
    rating = rating.strip()
    return rating

In [ ]:
#apply cleaning functions to data set and save to csv
df['company_credit_rating'] = df['creditrating'].apply(extract_credit_rating)
df['agency'] = df['creditrating'].apply(extract_credit_agency)

df.to_csv("merged_with_ratings.csv")